openapi: 3.0.3
info:
  title: QuickGig API
  version: 1.0.0
  description: |
    API contract v1 for QuickGig web/mobile clients.
servers:
  - url: http://127.0.0.1:8000/api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Token

  schemas:
    Role:
      type: string
      enum: [worker, employer]

    User:
      type: object
      required: [id, name, phone, role]
      properties:
        id:
          type: integer
        name:
          type: string
        phone:
          type: string
          example: "380673334455"
        email:
          type: string
          nullable: true
        role:
          $ref: '#/components/schemas/Role'
        rating:
          type: number
          format: float
        reviews_count:
          type: integer

    AuthResponse:
      type: object
      required: [token, user]
      properties:
        token:
          type: string
        user:
          $ref: '#/components/schemas/User'

    Shift:
      type: object
      required: [id, employer_id, title, pay_per_hour, start_at, end_at, latitude, longitude, work_format, required_workers]
      properties:
        id:
          type: integer
        employer_id:
          type: integer
        title:
          type: string
        details:
          type: string
          nullable: true
        address:
          type: string
        pay_per_hour:
          type: integer
        start_at:
          type: string
          format: date-time
        end_at:
          type: string
          format: date-time
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        work_format:
          type: string
          enum: [online, offline]
        required_workers:
          type: integer
        applications_count:
          type: integer
        pending_applications_count:
          type: integer
        accepted_applications_count:
          type: integer
        rejected_applications_count:
          type: integer
        employer:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            rating:
              type: number
              format: float
            reviews_count:
              type: integer

paths:
  /health:
    get:
      summary: API liveness check
      responses:
        '200':
          description: OK

  /register:
    post:
      summary: Register user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, phone, password, role]
              properties:
                name:
                  type: string
                phone:
                  type: string
                  pattern: '^380\d{9}$'
                email:
                  type: string
                  nullable: true
                password:
                  type: string
                  minLength: 6
                role:
                  $ref: '#/components/schemas/Role'
      responses:
        '201':
          description: Registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [phone, password]
              properties:
                phone:
                  type: string
                  pattern: '^380\d{9}$'
                password:
                  type: string
      responses:
        '200':
          description: Authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /me:
    get:
      summary: Current authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'

  /logout:
    post:
      summary: Logout current token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logged out

  /shifts:
    get:
      summary: List shifts
      responses:
        '200':
          description: Shifts list
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Shift'
    post:
      summary: Create shift (employer only)
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Shift created

  /shifts/{id}:
    get:
      summary: Shift detail
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Shift detail
    patch:
      summary: Update shift (employer only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                details:
                  type: string
                address:
                  type: string
                pay_per_hour:
                  type: integer
                start_at:
                  type: string
                  format: date-time
                end_at:
                  type: string
                  format: date-time
                latitude:
                  type: number
                longitude:
                  type: number
                work_format:
                  type: string
                  enum: [online, offline]
                required_workers:
                  type: integer
                status:
                  type: string
                  enum: [open, closed]
      responses:
        '200':
          description: Shift updated

  /shifts/{id}/apply:
    post:
      summary: Apply to shift (worker only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Application created

  /my/shifts:
    get:
      summary: Employer shifts
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List

  /my/applications:
    get:
      summary: Worker applications
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List

  /applications/{id}/status:
    patch:
      summary: Update application status (employer)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Updated

  /reviews:
    post:
      summary: Create review
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Review created
